<?php

require_once 'configaration.php';
require_once 'ShurjopayValidation.php';

/**
 * PHP plugin class to connect and integrate with shurjoPay payment gateway API.
 * There are three mendatory public functions which will need to access shurjoPay.<br>
 * 1. authenticate()-> makes client authenticate
 * 2. makePayment()-> generates payment url for checkout
 * 3. verifyPayment()-> makes payment verification
 * prepareCurlRequest, prepareTransactionPayload & logInfo() are internally.
 *
 * @author Md Wali Mosnad Ayshik
 * @since 2022-10-15
 */
class ShurjopayPlugin
{
    /** shurjopay payment gateway API endpoint */
    private $LOG_LOCATION;
    private $LOG_FILE;
    private $SP_TOKEN;
    private $SP_STORE;

    public function __construct()
    {
        $this->authentication_url = SHURJOPAY_API . "api/get_token";
        $this->checkout_url = SHURJOPAY_API . "api/secret-pay";
        $this->verification_url = SHURJOPAY_API . "api/verification";
        $this->LOG_LOCATION = !str_contains(SP_LOG_LOCATION, "sp-plugin-php")
            ? SP_LOG_LOCATION . "sp-plugin-php" : SP_LOG_LOCATION;
        $this->LOG_FILE = $this->LOG_LOCATION . "shurjopay-plugin.log";
    }

    public function authenticate()
    {
        if (empty(SP_USERNAME) || empty(SP_PASSWORD)) {
            $this->sp_log("Authentication process can not continue as username or password is empty");
            exit("Authentication process can not continue as username or password is empty");
        }

        $postFields = array('username' => SP_USERNAME, 'password' => SP_PASSWORD);

        $response = $this->getHttpResponse($this->authentication_url, 'POST', $postFields, array(''));
        if (!$response) {
            $this->sp_log("Authentication failed");
            return null;
        }
        $response = json_decode(json_encode($response), true);
        $this->SP_TOKEN = $response['token'];
        $this->SP_STORE = $response['store_id'];
        return $this->SP_TOKEN;
    }

    public function makePayment($payload)
    {
        if (!checkInternetConnection()) {
            // TODO print_r or log it ? decide ? Wali + Redoy
            print_r("Your have no internet connection! Please check your internet connection.");
            exit;
        }
        $this->check_token("Payment process can not continue as no authentication token is available");

        $trxn_data = $this->prepareTransactionPayload($payload);
        #All data from payload in trxn_data as array.
        // TODO
        if (Validation($trxn_data)) {
            $header = array(
                'Content-Type:application/json',
                'Authorization: Bearer ' . json_decode($trxn_data)->token
            );

            try {
                $response = $this->getHttpResponse($this->checkout_url, 'POST', $trxn_data, $header);
                #send all requried data to prepareCurlRequest
                if (!empty($response->checkout_url)) {
                    $this->logInfo("Payment URL has been generated by shurjoPay!");
                    return header('Location: ' . $response->checkout_url);
                    #redirecting to checkout_url of shurjoPay.
                } else {
                    return $response; //object
                }
            } catch (Exception $e) {
                return $e->getMessage();
            }
        }
    }

    private function check_token($msg) {
        if (!$this->SP_TOKEN) {
            $this->SP_TOKEN = $this->authenticate();
            if (!$this->SP_TOKEN) {
                $this->sp_log($msg);
                exit($msg);
            }
        }
        return true;
    }

    public function verifyPayment($shurjopay_order_id)
    {
        $this->check_token("Verification process can not continue as no authentication token is available");
        $header = array(
            'Content-Type:application/json',
            'Authorization: Bearer ' . $this->SP_TOKEN
        );
        $postFields = json_encode(array('order_id' => $shurjopay_order_id));
        try {
            $response = $this->getHttpResponse($this->verification_url, 'POST', $postFields, $header);
            $this->sp_log("Payment verification for ".$shurjopay_order_id." was done successfully");
            return $response;
        } catch (Exception $e) {
            $this->sp_log("Invalid order id: " . $shurjopay_order_id . ". \n" . $e->getMessage());
            return $e->getMessage();
        }
    }

    public function prepareTransactionPayload($payload)
    {
        return json_encode(
            array(
                // store information
                'token' => $this->SP_TOKEN,
                'store_id' => $this->SP_STORE,
                'prefix' => SP_PREFIX,
                'currency' => $payload['currency'],
                'return_url' => $this->SP_CALLBACK,
                'cancel_url' => $this->SP_CALLBACK,
                'amount' => $payload['amount'],
                // Order information
                'order_id' => SP_PREFIX . uniqid(),
                'discsount_amount' => $payload['discsount_amount'],
                'disc_percent' => $payload['disc_percent'],
                // Customer information
                'client_ip' => $_SERVER['REMOTE_ADDR'] ?: ($_SERVER['HTTP_X_FORWARDED_FOR'] ?: $_SERVER['HTTP_CLIENT_IP']),
                'customer_name' => $payload['customer_name'],
                'customer_phone' => $payload['customer_phone'],
                'customer_email' => $payload['email'],
                'customer_address' => $payload['customer_address'],
                'customer_city' => $payload['customer_city'],
                'customer_state' => $payload['customer_state'],
                'customer_postcode' => $payload['customer_postcode'],
                'customer_country' => $payload['customer_country'],
                'value1' => $payload['value1'],
                'value2' => $payload['value2'],
                'value3' => $payload['value3'],
                'value4' => $payload['value4']
            )
        );
    }

    /**
     * Prepare and send HTTP requests using curl library and process response.
     *
     * @param $url Destination URL
     * @param $method POST or GET
     * @param $payload_data
     * @param $header Header options
     * @return mixed
     */
    public function getHttpResponse($url, $method, $payload_data, $header)
    {
        try {
            $curl = curl_init();
            curl_setopt_array(
                $curl,
                array(
                    CURLOPT_URL => $url,
                    CURLOPT_HTTPHEADER => $header,
                    CURLOPT_POST => 1,
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_POSTFIELDS => $payload_data,
                    CURLOPT_CUSTOMREQUEST => $method,
                    CURLOPT_ENCODING => '',
                    CURLOPT_MAXREDIRS => 10,
                    CURLOPT_TIMEOUT => 0,
                    CURLOPT_FOLLOWLOCATION => true,
                    #If HTTPS not working in local project
                    #Please Uncomment |CURLOPT_SSL_VERIFYPEER|
                    #NOTE-Please Comment Again before going Live
                    //CURLOPT_SSL_VERIFYPEER => 0,
                )
            );
            $response = curl_exec($curl);
            return (json_decode($response));
        } catch (Exception $e) {
            $this->sp_log("Shurjopay plugin has failed to initialize Curl! \n" . $e->getMessage());
        } finally {
            curl_close($curl);
        }
        return null;
    }

    public function sp_log($log_msg)
    {
        if (!isset($this->LOG_LOCATION)) return;
        if (!file_exists($this->LOG_FILE)) {
            if (!mkdir($this->LOG_LOCATION, 0775, true)) {
                error_log("Failed to create directory at " . $this->LOG_LOCATION);
                unset($this->LOG_LOCATION);
            }
        }
        $log_msg = gmdate('Y-m-d H:i:s') . " ShurjopayPlugin: " . $log_msg;
        file_put_contents($this->LOG_FILE, $log_msg . "\n", FILE_APPEND);
    }
}

// Polyfill for PHP 4 - PHP 7, safe to utilize with PHP 8
if (!function_exists('str_contains')) {
    function str_contains($haystack, $needle)
    {
        return empty($needle) || strpos($haystack, $needle) !== false;
    }
}